# Site
#repository:
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Sébastien Coavoux
title: Devops, Kubernetes, GNU/Linux
email: contact@azoplee.com
#phone: Your phone number (optional)
#website: Your website (eg. https://google.com)(optional)
available: true
next_availability: in March 2020
#source: ./en
#destination: ./en

darkmode: true

# Social links
#github_username:  jekyll
linkedin_username: scoavoux

# About Section
# about_title: About Me (Use this to override about section title)
#about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  I have 8 years experience in development and operations (Devops). I have a strong experience cloud technologies, containers, free and open source software and systems monitoring. I’m familiar with Agile methodology, got a good team spirit and can communicate easily. The diversity of mi missions allowed me to be more open-minded and be more autonomous.
  My main objective : ship work the way I would like to receive it

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
#more_content: | # this will include new lines to allow paragraphs

# Footer
#footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
